# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae49e12fa99c6e06820b66adba768e3f2a34657ece01a0704b18a8dae1499addcb05a6120f2a383d4b70515fad6fb373532955fe8654edfbe6639fe8322dfc7

test:
  secret_key_base: 084088a53a3aaee5f077dd4ab2ebffdc30e48c7b7814b4adc2b87adc4034e8d3f029172ba32784d42d4cc9180288e03d227d936442753e10ec76b3be0b4620f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
